version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo "Autenticado com sucesso!"
  build:
    commands:
      - echo "Construindo a imagem Docker..."
      - TIMESTAMP=$(date +%Y%m%d%H%M)
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:$TIMESTAMP
  post_build:
    commands:
      - echo "Empurrando a imagem Docker para o Amazon ECR..."
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:$TIMESTAMP
      - echo '[{"name":"backend","imageUri":"'"$ECR_URI:$IMAGE_TAG"'"}]' > imagedefinitions.json
      - echo "Build e push concluídos com sucesso!"
artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
  discard-paths: no
