services:
  connect_database:
    image: postgres
    container_name: connect_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
